baseURL: "https://marekond.github.io/"
title: MarekOnd
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: false

params:
  math: true
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: MarekOnd
  description: "This page will contain my projects and things I find interesting"
  keywords: [Blog, Portfolio, PaperMod]
  author: marekond
  # author: ["Me", "You"] # multiple authors
  images: ["https://github.com/MarekOnd.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  

  

  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "https://github.com/MarekOnd.png"
    favicon16x16: "https://github.com/MarekOnd.png"
    favicon32x32: "https://github.com/MarekOnd.png"
    apple_touch_icon: "https://github.com/MarekOnd.png"
    safari_pinned_tab: "https://github.com/MarekOnd.png"

  label:
    text: "Home"
    icon: https://github.com/MarekOnd.png
    iconHeight: 45

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Ondřej Marek
    subtitle: $e^{\mathrm{i}\pi} = -1$
    imageUrl: "https://github.com/MarekOnd.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Monkey vortex"
    buttons:
      

  # home-info mode
  homeInfoParams:
    Title: "Greetings"
    Content: Welcome to my workfolio

  socialIcons:
    - name: github
      url: "https://github.com/MarekOnd"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page
    responsiveImages: false

  editPost:
    URL: "https://github.com/MarekOnd/MarekOnd.github.io/content/en"
    Text: "Edit" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 1
    #- identifier: archives
    #  name: Archive
    #  url: /archives/
    #  weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 3
    - identifier: links
      name: Links
      url: /links/
      weight: 5
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 4
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: false
    # noClasses: false
    style: monokai
python:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: false
    noClasses: false
    style: monokai


outputs:
  home:
    - HTML
    - RSS
    - JSON
    
goldmark:
  parser:
    unsafe: true
    attribute:
      block: true
tableOfContents:
  endLevel: 5
  ordered: false
  startLevel: 2
security:
  enableInlineShortcodes: true



defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  cz:
    contentDir: content/cz
    disabled: false
    languageCode: cz-CZ
    languageDirection: ltr
    languageName: Czech
    params:
      subtitle: 
      editPost:
        URL: "https://github.com/MarekOnd/MarekOnd.github.io/content/cz"
        Text: "Upravit" # edit text
        appendFilePath: true
      label:
        text: "Domů"
        icon: https://github.com/MarekOnd.png
        iconHeight: 45
        title: MarekOnd
    weight: 2
    menu:
      main:
        - identifier: about
          name: "O mně"
          url: /about/
          weight: 1
        - identifier: posts
          name: Blog
          url: /posts/
          weight: 2
        #- identifier: archive
        #  name: Archiv
        #  url: /archive/
        #  weight: 10
        - identifier: search
          name: Hledat
          url: /search/
          weight: 3
        - identifier: links
          name: Odkazy
          url: /links/
          weight: 5
        - identifier: tags
          name: Tagy
          url: /tags/
          weight: 4
    
  en:
    contentDir: content/en
    disabled: false
    languageCode: en-GB
    languageDirection: ltr
    languageName: English
    params:
      subtitle: Projects, blog
    title: MarekOnd
    weight: 1
